### ISSUE TITLE
Duration of a unit test must be at least 1

### ISSUE THREAD

**Issue by d-claassen** [mageddo/mocha-sonar-generic-test-coverage#2]
The xsd provided by sonar describes the attribute `duration` as a `positiveInteger`:

``` XML
<xs:attribute name="duration" type="xs:positiveInteger" use="required"/>
```

This means it must be bigger than 0. It'd be nice if this plugin would catch such situations, and prevent any issues. This also means it should not set the default duration to 0, if no time is provided by the test result.

``` javascript
append(util.format(
    '       <testCase name="%s" duration="%d">',
    espape(test.titleId), test.duration != undefined ? test.duration : 0
));
```

**Comment by mageddo** [comment]
@d-claassen Makes sense, so the report generation will fail in this case with this constraint validation

**Comment by mageddo** [comment]
That  was fixed  at [this commit ](https://github.com/mageddo/mocha-sonar-generic-test-coverage/commit/d5aac4bf1ae083e545fc87e33ed3de438a9a029d) and is at master
